license="All rights reserved"

modLoader="javafml"

loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

[[mods]] #mandatory

modId="siegeweapons"

version="0.2.2"

displayName="Siege Weapons Mod"
updateJSONURL="https://raw.githubusercontent.com/talhanation/siegeweapons/main/update.json"
displayURL="https://modrinth.com/mod/siege-weapons/versions"

logoFile="logo.png"

credits="talhanation"
authors="talhanation"

# The description text for the mod (multi line!) (#mandatory)
description='''
This Mod adds medieval siege weaopons into Minecraft.
'''

